URI Change to GUID; Tests for IObjects and BHoMObjects (PR #41)
BHoM/RDF_Prototypes pull request #68
Opened 2023-02-22 12:53 UTC by polnischfrosch

### Issues addressed by this PR

Closes #41 

Changed the composition of Individuals URI from Hash to GUID
Created new Tests in ToTTLTests to check the new URI for IObjects, BHoMObjects and non serialized IGeometry Objects.

2023-02-28 17:35 UTC, alelom commented on RDF_Tests/ToTTLTests.cs
> +            Assert.IsTrue(TTLGraph.Contains(room.BHoM_Guid.ToString()));
This check should be replaced with:
```cs
string roomUrl = Flurl.Url.Combine(cSharpGraph.OntologySettings.ABoxSettings.IndividualsBaseAddress, room.BHoM_Guid.ToString());
Assert.IsTrue(TTLGraph.Contains(roomUrl));
```
(will add a commit for you)

2023-02-28 17:36 UTC, alelom commented on RDF_Tests/ToTTLTests.cs
> +            Assert.IsTrue(TTLGraph.Contains(nurbsGuid));
This check should be replaced with:
```cs
string nurbsUrl = Flurl.Url.Combine(cSharpGraph.OntologySettings.ABoxSettings.IndividualsBaseAddress, nurbsGuid.ToString());
Assert.IsTrue(TTLGraph.Contains(nurbsUrl));
```
(will add a commit for you)

2023-02-28 17:41 UTC, alelom requested changes
Thanks a lot for this @polnischfrosch ! Looks great and I really liked the reasoning you've put.
However, there probably is still some work to be done. If you inspect the output TTL of the first test case you've made (the one about the `Room`) you will see, under individuals:
```
### http://individuals.address/10b49b3d-f976-bb2a-4a04-2a7dc83a56b8
<http://individuals.address/10b49b3d-f976-bb2a-4a04-2a7dc83a56b8> rdf:type owl:NamedIndividual ,
		:BH.oM.Architecture.Elements.Room ;
		:BH.oM.Architecture.Elements.Room.Perimeter "ew0KICAiJHR5cGUiOiAiQkguRW5naW5lLkFkYXB0ZXJzLlJERi5Db252ZXJ0K1R5cGVXcmFwcGVyYDFbW0JILm9NLkdlb21ldHJ5LlBvbHlsaW5lLCBHZW9tZXRyeV9vTV1dLCBSREZfRW5naW5lIiwNCiAgIlZhbHVlIjogew0KICAgICIkdHlwZSI6ICJCSC5vTS5HZW9tZXRyeS5Qb2x5bGluZSwgR2VvbWV0cnlfb00iLA0KICAgICJDb250cm9sUG9pbnRzIjogew0KICAgICAgIiR0eXBlIjogIlN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbQkgub00uR2VvbWV0cnkuUG9pbnQsIEdlb21ldHJ5X29NXV0sIFN5c3RlbS5Qcml2YXRlLkNvcmVMaWIiLA0KICAgICAgIiR2YWx1ZXMiOiBbDQogICAgICAgIHsNCiAgICAgICAgICAiJHR5cGUiOiAiQkgub00uR2VvbWV0cnkuUG9pbnQsIEdlb21ldHJ5X29NIiwNCiAgICAgICAgICAiWCI6IDAuMCwNCiAgICAgICAgICAiWSI6IDAuMCwNCiAgICAgICAgICAiWiI6IDAuMA0KICAgICAgICB9LA0KICAgICAgICB7DQogICAgICAgICAgIiR0eXBlIjogIkJILm9NLkdlb21ldHJ5LlBvaW50LCBHZW9tZXRyeV9vTSIsDQogICAgICAgICAgIlgiOiA1LjAsDQogICAgICAgICAgIlkiOiAwLjAsDQogICAgICAgICAgIloiOiAwLjANCiAgICAgICAgfSwNCiAgICAgICAgew0KICAgICAgICAgICIkdHlwZSI6ICJCSC5vTS5HZW9tZXRyeS5Qb2ludCwgR2VvbWV0cnlfb00iLA0KICAgICAgICAgICJYIjogOTkuMCwNCiAgICAgICAgICAiWSI6IDAuMCwNCiAgICAgICAgICAiWiI6IDAuMA0KICAgICAgICB9DQogICAgICBdDQogICAgfQ0KICB9DQp9"^^:BH.oM.Adapters.RDF.Base64JsonSerialized;
		:BH.oM.Architecture.Elements.Room.Location "ew0KICAiJHR5cGUiOiAiQkguRW5naW5lLkFkYXB0ZXJzLlJERi5Db252ZXJ0K1R5cGVXcmFwcGVyYDFbW0JILm9NLkdlb21ldHJ5LlBvaW50LCBHZW9tZXRyeV9vTV1dLCBSREZfRW5naW5lIiwNCiAgIlZhbHVlIjogew0KICAgICIkdHlwZSI6ICJCSC5vTS5HZW9tZXRyeS5Qb2ludCwgR2VvbWV0cnlfb00iLA0KICAgICJYIjogMC4wLA0KICAgICJZIjogMC4wLA0KICAgICJaIjogMC4wDQogIH0NCn0="^^:BH.oM.Adapters.RDF.Base64JsonSerialized;
		:BH.oM.Base.BHoMObject.BHoM_Guid "de0774d0-f338-4fcf-9c9c-4c8b44ed3a29"^^xsd:string;
		:BH.oM.Base.BHoMObject.Name "first room object"^^xsd:string .
```
You can see how the address at `<http://individuals.address/10b49b3d-f976-bb2a-4a04-2a7dc83a56b8>` does not contain the Room Guid, that is listed below as `:BH.oM.Base.BHoMObject.BHoM_Guid "de0774d0-f338-4fcf-9c9c-4c8b44ed3a29"^^xsd:string;`. I think we want the address to be pointing at the correct individual ID, which for Room is the BHoM_Guid, whilst for Geometry is the Guid of the hash.

You tests failed to capture this because you were looking for the presence of the Guid or Guid of the Hash within the exported TTL, but: 
- the BHoM_Guid will always be present (as a property of the object);
- for IObjects, because the ontology identifier is never a property of the object, the check you've written should still be safe (in fact it does pass even if I change the check to my proposed version), but it is safer to check for the full URI (as it is the intended target of the identifier - being part of the URI).

For this reason, I think we should modify the check as I've proposed (will do a commit myself on this, I've added a Nuget package to make it simpler). Haven't had time to put thought on what else we need to do, but feel free to have another look or we can continue together.

2023-02-28 17:59 UTC, alelom commented on RDF_Tests/ToTTLTests.cs
> +            Assert.IsTrue(TTLGraph.Contains(room.BHoM_Guid.ToString()));
Done in https://github.com/BHoM/RDF_Prototypes/pull/68/commits/c0f70ecdd9093e071ee5bc2837888cd65306d24e

2023-02-28 17:59 UTC, alelom commented on RDF_Tests/ToTTLTests.cs
> +            Assert.IsTrue(TTLGraph.Contains(nurbsGuid));
Done in https://github.com/BHoM/RDF_Prototypes/pull/68/commits/c0f70ecdd9093e071ee5bc2837888cd65306d24e

2023-03-01 15:12 UTC, DiellzaElshani approved these changes
![image](https://user-images.githubusercontent.com/50298535/222180804-12dc0862-5417-4c66-ac2a-c623b6c9ed8e.png)
 works well on my end.

2023-03-01 15:13 UTC, alelom approved these changes

2023-03-02 17:48 UTC, alelom commented
I'm merging this bypassing branch protection as adding @polnischfrosch to the BHoM org still didn't solve the problem unfortunately. We will have to look into that.
![image](https://user-images.githubusercontent.com/6352844/222510258-b3eef97e-713e-4d0c-b7e0-4ba20d2434c9.png)

2023-03-02 17:49 UTC, merged