Rdf prototypes #69#70#71 restructuring ontology settings
BHoM/RDF_Prototypes pull request #73
Opened 2023-03-08 13:21 UTC by polnischfrosch

### Issues addressed by this PR

Closes #69 #70 #71

The class "OntologySettings" was changed to "GraphSettings" in the BasicSettings- and more elaborate component, as well as the Input for the TTLAdapter. Many instances of the GraphSettings class were also renamed for consistency, such as in Tests.
The Property "GeometryAsOntologyClass" was moved from the TBOX class to the ABOX class, all references such as in "IsOntologyClass", etc. were updated as well.

![DeserializedeDITED](https://user-images.githubusercontent.com/104036071/223720534-bd437be3-8c7b-408d-9051-b5b55caf83fe.png)

A "deserializeGeometry" Input was added to the "BasicGraphSettings", which can change if iGeometry objects are to be considered as a class or not. The result can be seen in the individual section of the TTL output.

![SerializedeDITED](https://user-images.githubusercontent.com/104036071/223720538-afd62841-5aa5-4b8d-bd4d-c47aba351e58.png)

Example for serialized option.

### Test files
[GraphSettingsTestFile#69#70#71.zip](https://github.com/BHoM/RDF_Prototypes/files/10920798/GraphSettingsTestFile.69.70.71.zip)

### Additional comments

2023-03-08 15:19 UTC, alelom requested changes

2023-03-08 15:19 UTC, alelom commented on RDF_Engine/Query/IsDataType.cs
> +            return !type.IsOntologyClass(aBoxSettings);
As mentioned in https://github.com/BHoM/RDF_Prototypes/issues/70#issuecomment-1460310928:
these methods that define the T-Box (IsDataType, IsDataProperty, etc.) should depend on the TBoxSettings, not the ABoxSettings.

Therefore, we should move the GeometryAsOntologyClass into the TBoxSettings.

2023-03-23 14:52 UTC, alelom approved these changes
Approving based on code review and unit tests. Haven't tried in Rhino, leaving @DiellzaElshani for that.

2023-03-23 15:01 UTC, DiellzaElshani approved these changes
Works well on my end when testing in from Rhino/Grasshopper. 

![image](https://user-images.githubusercontent.com/50298535/227244806-fa4af8d9-3ade-4a24-84cd-e0d308db78c2.png)

2023-03-23 15:01 UTC, merged